export const STOCK_NAMES_KO: Record<string, string> = {
  AA: "알코아",
  AAPL: "애플",
  AMD: "AMD",
  AMZN: "아마존",
  AON: "에이온",
  AVGO: "브로드컴",
  AXP: "아메리칸 익스프레스",
  BABA: "알리바바",
  BAC: "뱅크 오브 아메리카",
  BN: "브룩필드",
  BRKR: "브루커",
  CB: "처브",
  CRWV: "코어위브",
  CVX: "셰브론",
  EA: "일렉트로닉 아츠",
  ELV: "엘리번스 헬스",
  EXP: "이글 머티리얼스",
  FERG: "퍼거슨 엔터프라이즈",
  GEV: "GE 버노바",
  GOOG: "알파벳 클래스 C",
  GOOGL: "알파벳 클래스 A",
  HAL: "할리버튼",
  HHH: "하워드 휴즈 홀딩스",
  HTZ: "허츠 글로벌",
  INSM: "인스메드",
  IVV: "아이셰어즈 코어 S&P 500 ETF",
  KHC: "크래프트 하인즈",
  KO: "코카콜라",
  LRCX: "램리서치",
  LULU: "룰루레몬 애슬레티카",
  META: "메타 플랫폼스",
  MOH: "몰리나 헬스케어",
  MSFT: "마이크로소프트",
  MU: "마이크론 테크놀로지",
  NAMS: "뉴암스테르담 파마",
  NRG: "NRG 에너지",
  NTRA: "나테라",
  NVDA: "엔비디아",
  OXY: "옥시덴털 페트롤리엄",
  PFE: "화이자",
  PLTR: "팔란티어 테크놀로지스",
  QSR: "레스토랑 브랜즈 인터내셔널",
  RSP: "인베스코 S&P 500 동일가중 ETF",
  SE: "씨 리미티드",
  SEG: "시포트 엔터테인먼트",
  SLM: "SLM 코퍼레이션",
  SNDK: "샌디스크",
  SPY: "SPDR S&P 500 ETF",
  STM: "ST마이크로일렉트로닉스",
  TBBB: "BBB 푸즈",
  TFX: "텔레플렉스",
  TSM: "TSMC",
  UBER: "우버 테크놀로지스",
  UNP: "유니언 퍼시픽",
  V: "비자",
  VST: "비스트라",
  WCC: "웨스코 인터내셔널",
  WTW: "윌리스 타워스 왓슨",
  XLE: "에너지 셀렉트 섹터 SPDR ETF",
  YPF: "YPF",
};

export function formatStockLabel(ticker: string | null | undefined, issuerName: string) {
  if (!ticker) return issuerName;
  const normalized = ticker.toUpperCase();
  return `${STOCK_NAMES_KO[normalized] ?? issuerName} (${normalized})`;
}
