import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Building2, ChartNoAxesCombined, Landmark } from "lucide-react";
import { CurrencyNotice } from "@/components/currency-notice";
import { DataNotice } from "@/components/data-notice";
import { Container, EmptyState, Pill } from "@/components/ui";
import { getCompanyFacts, type FinancialMetric } from "@/lib/company-facts";
import { getStockSnapshot } from "@/lib/data/public";
import { formatDate, formatNumber, formatPercent } from "@/lib/format";
import { formatMoneyDual } from "@/lib/exchange-rate";
import { formatStockLabel } from "@/lib/stock-labels";
import { getStockResearch } from "@/lib/stock-research";

export async function generateMetadata({ params }: { params: Promise<{ ticker: string }> }): Promise<Metadata> {
  const { ticker } = await params;
  const data = await getStockSnapshot(ticker);
  const label = data ? formatStockLabel(data.ticker, data.issuerName) : ticker.toUpperCase();
  return { title: `${label} 기업 정보·재무제표·13F 보유 현황`, description: `${label}의 SEC 재무제표와 세계 투자자 13F 보유 현황을 한글로 확인하세요.`, keywords: [label, `${ticker} 주식`, `${ticker} 재무제표`, `${ticker} 13F`, `${ticker} PER`], alternates: { canonical: `/stocks/${ticker.toLowerCase()}` }, openGraph: { type: "article", title: `${label} 기업 정보와 13F 보유 현황`, description: `${label} SEC 재무제표와 기관 보유 내역` } };
}

const tabs = [["overview", "기업 정보"], ["holders", "보유 투자자"], ["financials", "재무제표"]] as const;

export default async function StockDetailPage({ params, searchParams }: { params: Promise<{ ticker: string }>; searchParams: Promise<{ tab?: string }> }) {
  const [{ ticker }, { tab = "overview" }] = await Promise.all([params, searchParams]);
  const data = await getStockSnapshot(ticker);
  if (!data) notFound();
  const facts = getCompanyFacts(data.ticker);
  const label = formatStockLabel(data.ticker, data.issuerName);
  const activeTab = tabs.some(([key]) => key === tab) ? tab : "overview";

  return <Container className="py-10 sm:py-14">
    <div className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900 p-7 text-white shadow-xl sm:p-10"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><Pill tone="green">SEC 기업·13F 정보</Pill><h1 className="mt-5 text-4xl font-extrabold leading-tight sm:text-6xl">{label}</h1><p className="mt-4 text-sm text-zinc-300">{`SEC 원문 발행사명 · ${data.issuerName}`}</p><p className="mt-2 font-mono text-xs text-zinc-500 dark:text-zinc-400">CUSIP {data.cusip}{facts ? ` · CIK ${facts.cik}` : ""}</p></div><div className="grid grid-cols-2 gap-3 text-sm"><div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3"><p className="text-xs text-zinc-400">13F 보유 기관</p><p className="mt-1 text-xl font-bold">{data.owners.length}곳</p></div><div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3"><p className="text-xs text-zinc-400">PER</p><p className="mt-1 text-sm font-bold">시세 미연동</p></div></div></div></div>
    <div className="my-6"><DataNotice compact /></div>
    <nav className="mb-8 flex gap-2 overflow-x-auto border-b border-zinc-200 dark:border-zinc-800" aria-label="종목 상세 탭">{tabs.map(([key, text]) => <Link key={key} href={`/stocks/${data.ticker.toLowerCase()}?tab=${key}`} className={`shrink-0 border-b-2 px-4 py-3 text-sm font-semibold ${activeTab === key ? "border-amber-600 text-amber-700" : "border-transparent text-zinc-500 dark:text-zinc-400 hover:text-zinc-800 dark:text-zinc-200"}`}>{text}</Link>)}</nav>
    {activeTab === "overview" && <Overview facts={facts} data={data} />}
    {activeTab === "holders" && <Holders data={data} />}
    {activeTab === "financials" && <Financials facts={facts} />}
  </Container>;
}

function Overview({ facts, data }: { facts: ReturnType<typeof getCompanyFacts>; data: NonNullable<Awaited<ReturnType<typeof getStockSnapshot>>> }) {
  const securityClasses = [...new Set(data.owners.map(({ holding }) => [holding.title_of_class, holding.put_call].filter(Boolean).join(" · ")).filter(Boolean))];
  const research = getStockResearch(data.ticker, facts?.entityName ?? data.issuerName, facts?.sicDescription, securityClasses);
  const dividend = facts?.metrics.dividendPerShare?.values[0];
  const dividendsPaid = facts?.metrics.dividendsPaid?.values[0];
  return <div className="space-y-6">
    <div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm p-6 sm:p-8"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-amber-50 text-amber-700"><Building2 className="size-5" /></div><div><p className="text-xs font-semibold uppercase text-amber-700">Company</p><h2 className="text-xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-100">기업 기본 정보</h2></div></div>{facts ? <dl className="mt-7 grid gap-5 sm:grid-cols-2"><Info label="SEC 등록명" value={facts.entityName} /><Info label="주식 종류" value={research.securityType} /><Info label="산업 분류" value={facts.sicDescription ?? "미제공"} /><Info label="SIC" value={facts.sic ?? "미제공"} /><Info label="설립 주" value={facts.stateOfIncorporation ?? "미제공"} /><Info label="회계연도 말" value={formatFiscalYearEnd(facts.fiscalYearEnd)} /><Info label="PER" value="실시간 주가 라이선스 미연동" /></dl> : <dl className="mt-7"><Info label="주식 종류" value={research.securityType} /></dl>}</section><section className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm p-6 sm:p-8"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-sky-50 text-sky-700"><Landmark className="size-5" /></div><div><p className="text-xs font-semibold uppercase text-sky-700">13F & Dividend</p><h2 className="text-xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-100">공개 보유·배당 현황</h2></div></div><p className="mt-6 text-sm leading-7 text-zinc-500 dark:text-zinc-400">현재 Investinfo에서 추적하는 최신 13F 기준으로 {data.owners.length}개 기관이 이 종목을 보고했습니다. 이는 현재 보유나 투자 추천을 의미하지 않습니다.</p><div className="mt-5 rounded-2xl bg-zinc-50 dark:bg-zinc-800/50 p-4"><p className="text-xs font-medium text-zinc-400">SEC XBRL 최근 배당 공시</p>{dividend ? <><p className="mt-2 text-2xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-100">${dividend.val.toLocaleString("ko-KR", { maximumFractionDigits: 4 })} <span className="text-sm text-zinc-400">/주</span></p><p className="mt-1 text-xs text-zinc-400">{formatDate(dividend.end)} · {dividend.form}</p></> : dividendsPaid ? <><p className="mt-2 text-xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-100">지급액 {formatMoneyDual(dividendsPaid.val)}</p><p className="mt-1 text-xs text-zinc-400">{formatDate(dividendsPaid.end)} · {dividendsPaid.form}</p></> : <p className="mt-2 text-sm font-medium text-zinc-500 dark:text-zinc-400">확인되는 공시값 없음</p>}</div><p className="mt-3 text-xs leading-5 text-zinc-400">최근 공시값은 연환산 배당금이나 배당수익률이 아닐 수 있습니다. 값이 없다고 무배당을 뜻하지 않습니다.</p><Link href={`/stocks/${data.ticker.toLowerCase()}?tab=holders`} className="mt-6 inline-flex items-center rounded-2xl bg-zinc-900 px-4 py-3 text-sm font-bold text-white hover:bg-amber-700">보유 투자자 확인</Link></section></div>
    <section className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm p-6 sm:p-8"><Pill tone="green">사업 이해</Pill><h2 className="mt-4 text-2xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-100">이 종목은 어떤 회사인가요?</h2><p className="mt-4 max-w-5xl text-sm leading-8 text-zinc-500 dark:text-zinc-400">{research.summary}</p><div className="mt-8 grid gap-4 lg:grid-cols-3"><ResearchList title="주요 수익원" items={research.revenueDrivers} tone="emerald" /><ResearchList title="미래 산업·관찰 포인트" items={research.futureThemes} tone="blue" /><ResearchList title="핵심 위험 요인" items={research.risks} tone="amber" /></div><p className="mt-5 text-xs leading-6 text-zinc-400">이 설명은 기업·산업을 이해하기 위한 편집 정보이며 미래 수익률 예측이나 매수·매도 추천이 아닙니다. 최신 사업 변화는 해당 기업의 10-K·10-Q를 함께 확인하세요.</p></section>
  </div>;
}

function Holders({ data }: { data: NonNullable<Awaited<ReturnType<typeof getStockSnapshot>>> }) { return <><section><h2 className="text-2xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-100">최신 공시 기준 보유 투자자</h2><div className="mt-2"><CurrencyNotice /></div><div className="mt-5 overflow-x-auto rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-zinc-50 dark:bg-zinc-800/50 text-xs text-zinc-500 dark:text-zinc-400"><tr><th className="px-4 py-3">투자자 / 제출 기관</th><th className="px-4 py-3">보고 기준일</th><th className="px-4 py-3 text-right">수량</th><th className="px-4 py-3 text-right">보고 가치</th><th className="px-4 py-3 text-right">13F 내 비중</th></tr></thead><tbody>{data.owners.map(({ holding, investor, filing }) => <tr key={holding.id ?? `${investor.id}-${holding.cusip}`} className="border-t border-zinc-100 dark:border-zinc-800/50"><td className="px-4 py-4"><Link href={`/investors/${investor.slug}`} className="font-bold text-amber-700 hover:underline">{investor.display_name}</Link><p className="mt-1 text-xs text-zinc-500 dark:text-zinc-400">{investor.firm_name}</p></td><td className="px-4 py-4 text-zinc-500 dark:text-zinc-400">{formatDate(filing.report_date)}</td><td className="px-4 py-4 text-right font-mono">{formatNumber(Number(holding.shares))}</td><td className="px-4 py-4 text-right font-mono">{formatMoneyDual(Number(holding.value_usd))}</td><td className="px-4 py-4 text-right font-mono font-medium">{formatPercent(Number(holding.portfolio_weight))}</td></tr>)}</tbody></table></div></section><section className="mt-10"><h2 className="text-2xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-100">분기별 보고 수량</h2><p className="mt-2 text-sm text-zinc-500 dark:text-zinc-400">실제 거래 시점이나 현재 수량이 아닌 13F 스냅숏 기록입니다.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{data.history.map((holding, index) => { const owner = data.owners.find((item) => item.investor.id === holding.investor_id)?.investor; return <div key={`${holding.filing_id}-${index}`} className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm p-5"><div className="flex items-center justify-between"><p className="font-medium text-zinc-800 dark:text-zinc-200">{owner?.display_name ?? "제출 기관"}</p><span className="text-xs text-zinc-400">{formatDate(holding.report_date)}</span></div><p className="mt-3 text-lg font-bold tracking-tight text-zinc-900 dark:text-zinc-100">{formatNumber(Number(holding.shares))} <span className="text-xs font-medium text-zinc-400">{holding.share_type}</span></p></div>; })}</div></section></>;  }

function Financials({ facts }: { facts: ReturnType<typeof getCompanyFacts> }) { if (!facts || !Object.keys(facts.metrics).length) return <EmptyState title="SEC 재무제표 데이터가 없습니다" description="ETF 또는 외국 발행사처럼 SEC companyfacts XBRL이 제공되지 않는 종목일 수 있습니다." />; return <section><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-violet-50 text-violet-700"><ChartNoAxesCombined className="size-5" /></div><div><h2 className="text-2xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-100">SEC 재무제표 주요 항목</h2><p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">10-K·10-Q XBRL 보고값이며 단위와 기간을 함께 확인하세요.</p></div></div><div className="mt-3"><CurrencyNotice /></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(facts.metrics).map(([key, metric]) => <MetricCard key={key} metric={metric} />)}</div><div className="mt-8 rounded-2xl border border-sky-200 bg-sky-50 p-5 text-sm leading-7 text-sky-900"><strong>PER을 표시하지 않는 이유:</strong> PER 계산에는 현재 주가가 필요합니다. Investinfo는 상업적 사용이 검증된 실시간 시세 공급원을 아직 연결하지 않았으므로 추정값을 제공하지 않습니다. 배당 항목 역시 SEC XBRL에 공시된 과거 값이며 예상 배당이나 배당수익률이 아닙니다.</div></section>; }

function MetricCard({ metric }: { metric: FinancialMetric }) { const latest = metric.values[0]; const valueLabel = (value: number) => metric.unit === "USD" ? formatMoneyDual(value) : `$${value.toLocaleString("ko-KR", { maximumFractionDigits: 4 })}/주`; return <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm p-5"><p className="text-sm font-medium text-zinc-500 dark:text-zinc-400">{metric.label}</p><p className="mt-3 text-xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100">{valueLabel(latest.val)}</p><p className="mt-2 text-xs text-zinc-400">{formatDate(latest.end)} · {latest.form}</p>{metric.values.slice(1, 4).map((value) => <div key={`${value.end}-${value.form}`} className="mt-3 flex justify-between gap-3 border-t border-zinc-100 dark:border-zinc-800/50 pt-3 text-xs"><span className="shrink-0 text-zinc-400">{formatDate(value.end)}</span><span className="text-right font-mono font-medium text-zinc-500 dark:text-zinc-400">{valueLabel(value.val)}</span></div>)}</div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium text-zinc-400">{label}</dt><dd className="mt-1 text-sm font-bold text-zinc-700 dark:text-zinc-300">{value}</dd></div>; }
function ResearchList({ title, items, tone }: { title: string; items: string[]; tone: "emerald" | "blue" | "amber" }) { const styles = { emerald: "border-amber-100 bg-amber-50/70 text-amber-950", blue: "border-sky-100 bg-sky-50/70 text-sky-950", amber: "border-amber-100 bg-amber-50/70 text-amber-950" }; return <div className={`rounded-2xl border p-5 ${styles[tone]}`}><h3 className="font-bold">{title}</h3><ul className="mt-4 space-y-3 text-sm leading-6">{items.map((item) => <li key={item} className="flex gap-2"><span aria-hidden="true">•</span><span>{item}</span></li>)}</ul></div>; }
function formatFiscalYearEnd(value?: string) { return value && value.length === 4 ? `${value.slice(0, 2)}월 ${value.slice(2)}일` : "미제공"; }
