import Link from "next/link";
import { ArrowRight, BookOpen, CalendarDays, Layers3, Search, Sparkles } from "lucide-react";
import { InvestorAvatar } from "@/components/investor-avatar";
import { StockLabelLink } from "@/components/stock-label-link";
import { Container, EmptyState, Pill, SectionTitle } from "@/components/ui";
import { learnPosts } from "@/content/learn/posts";
import { getInvestors, getOverlap, getRecentFilings, getRecentNewPositions } from "@/lib/data/public";
import { formatDate } from "@/lib/format";
import { formatMoneyDual } from "@/lib/exchange-rate";

export default async function HomePage() {
  const [investors, filings, overlap, newPositions] = await Promise.all([getInvestors(), getRecentFilings(5), getOverlap(), getRecentNewPositions(6)]);
  return <>
    <section className="relative overflow-hidden border-b border-stone-200 bg-[#fffdf8]"><Container className="relative grid items-center gap-12 py-16 sm:py-24 lg:grid-cols-[1.05fr_.95fr] lg:py-24"><div><div className="inline-flex items-center gap-2 rounded-full border border-teal-200 bg-teal-50 px-3.5 py-2 text-xs font-black text-teal-800">SEC 13F 공식 공시 기반</div><h1 className="mt-6 max-w-3xl text-3xl font-black leading-[1.16] text-stone-950 sm:text-6xl sm:leading-[1.12]">세계적인 투자자들의<br /><span className="text-teal-700">공개 포트폴리오 리서치</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-stone-600">워런 버핏부터 국민연금까지, 공개된 미국 주식 보유 내역과 분기별 변화를 차분하게 비교해보세요.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/investors" className="inline-flex items-center gap-2 rounded-lg bg-stone-950 px-5 py-3.5 text-sm font-black text-white shadow-lg shadow-stone-950/10 hover:bg-teal-800">포트폴리오 보기 <ArrowRight className="size-4" /></Link><Link href="/stocks" className="inline-flex items-center gap-2 rounded-lg border border-stone-300 bg-white px-5 py-3.5 text-sm font-black text-stone-800 shadow-sm hover:border-teal-300 hover:bg-teal-50"><Search className="size-4" /> 종목 검색</Link></div><div className="mt-10 grid max-w-2xl grid-cols-3 gap-3 border-t border-stone-200 pt-6"><div><p className="text-2xl font-black text-stone-950">{investors.length}곳</p><p className="mt-1 text-xs font-semibold text-stone-500">추적 투자자·기관</p></div><div><p className="text-2xl font-black text-stone-950">분기별</p><p className="mt-1 text-xs font-semibold text-stone-500">공시 변화 비교</p></div><div><p className="text-2xl font-black text-stone-950">100%</p><p className="mt-1 text-xs font-semibold text-stone-500">SEC 공개 원문</p></div></div></div>
      <div className={`grid gap-3 border border-stone-200 bg-white/70 p-3 shadow-2xl shadow-stone-200/70 sm:p-4 ${investors.length > 1 ? "grid-cols-2" : "mx-auto w-full max-w-sm"}`}>{investors.slice(0, 4).map((investor) => <Link key={investor.id} href={`/investors/${investor.slug}`} className="rounded-lg border border-stone-200 bg-[#fffdf8] p-4 transition hover:-translate-y-0.5 hover:border-teal-300 hover:shadow-lg"><InvestorAvatar slug={investor.slug} name={investor.display_name} className="aspect-square w-full rounded-md" /><p className="mt-4 line-clamp-1 text-sm font-black text-stone-950">{investor.display_name}</p><p className="mt-1 line-clamp-1 text-xs text-stone-500">{investor.firm_name}</p></Link>)}</div>
    </Container></section>
    <Container className="space-y-16 py-14 sm:py-20">
      <section><SectionTitle title="주요 투자자 포트폴리오" description="인물과 관련된 실제 SEC 제출 기관의 최신 13F를 기준으로 합니다." href="/investors" /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{investors.slice(0, 6).map((investor) => <Link key={investor.id} href={`/investors/${investor.slug}`} className="group flex items-center gap-4 rounded-lg border border-stone-200 bg-white/75 p-4 shadow-sm hover:border-teal-300 hover:bg-white hover:shadow-md"><InvestorAvatar slug={investor.slug} name={investor.display_name} className="size-16 rounded-md" /><div className="min-w-0 flex-1"><h3 className="truncate font-black text-stone-950 group-hover:text-teal-800">{investor.display_name}</h3><p className="mt-1 truncate text-xs text-stone-500">{investor.firm_name}</p></div><ArrowRight className="size-4 text-stone-300 group-hover:text-teal-700" /></Link>)}</div></section>
      <section className="grid gap-8 lg:grid-cols-2"><div><SectionTitle title="최근 제출된 13F" description="SEC 제출일 기준 최신 공시" />{filings.length ? <div className="overflow-hidden rounded-lg border border-stone-200 bg-white/75 shadow-sm">{filings.map((filing) => <Link key={filing.id} href={`/investors/${filing.investor?.slug}`} className="flex items-center justify-between gap-4 border-b border-stone-100 p-4 last:border-0 hover:bg-teal-50/60"><div><p className="font-bold text-stone-900">{filing.investor?.display_name ?? "기관"}</p><p className="mt-1 text-xs text-stone-500">보고 기준일 {formatDate(filing.report_date)}</p></div><span className="flex items-center gap-1 text-xs font-semibold text-stone-500"><CalendarDays className="size-4" /> {formatDate(filing.filing_date)}</span></Link>)}</div> : <EmptyState title="수집된 공시가 없습니다" description="최신 SEC 13F 수집 후 표시됩니다." />}</div>
        <div><SectionTitle title="여러 기관이 함께 보유" description="최신 보고 분기의 CUSIP 기준" href="/overlap" />{overlap.length ? <div className="overflow-hidden rounded-lg border border-stone-200 bg-white/75 shadow-sm">{overlap.slice(0, 5).map((item) => <div key={item.key} className="flex items-center justify-between gap-4 border-b border-stone-100 p-4 last:border-0"><div className="min-w-0"><p className="truncate font-bold text-stone-900"><StockLabelLink ticker={item.ticker} issuerName={item.issuerName} /></p><p className="mt-1 text-xs text-stone-500">{item.ticker ? `CUSIP ${item.cusip}` : "ticker 미확인"}</p></div><Pill tone="blue">{item.owners.length}개 기관</Pill></div>)}</div> : <EmptyState title="겹치는 종목이 없습니다" description="2개 이상의 기관 데이터가 있을 때 계산됩니다." />}</div></section>
      <section><SectionTitle title="최근 분기 신규 편입" description="이전 정보표에는 없고 현재 분기에 나타난 CUSIP 기준" />{newPositions.length ? <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{newPositions.map((item) => <div key={`${item.current_filing_id}-${item.cusip}`} className="rounded-lg border border-stone-200 bg-white/75 p-5 shadow-sm"><Sparkles className="size-5 text-teal-700" /><p className="mt-3 line-clamp-1 font-black"><StockLabelLink ticker={item.ticker} issuerName={item.issuer_name} /></p><p className="mt-2 text-xs text-stone-500">{item.investor?.display_name} · {formatMoneyDual(item.current_value_usd)}</p></div>)}</div> : <EmptyState title="비교 가능한 신규 편입 데이터가 없습니다" description="최소 두 개 분기가 수집되면 표시됩니다." />}</section>
      <section><SectionTitle title="투자를 이해하는 기본 가이드" description="공시를 매매 신호로 오해하지 않기 위한 핵심 개념" href="/learn" /><div className="grid gap-4 md:grid-cols-3">{learnPosts.slice(0, 3).map((post, index) => <Link key={post.slug} href={`/learn/${post.slug}`} className="group rounded-lg border border-stone-200 bg-white/75 p-6 shadow-sm hover:border-teal-300 hover:bg-white"><div className="grid size-10 place-items-center rounded-lg bg-stone-950 text-teal-200">{index === 0 ? <BookOpen className="size-5" /> : <Layers3 className="size-5" />}</div><p className="mt-5 text-xs font-black uppercase text-teal-700">{post.category}</p><h3 className="mt-2 text-xl font-black leading-8 group-hover:text-teal-800">{post.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-stone-500">{post.description}</p></Link>)}</div></section>
      <aside className="rounded-lg border border-stone-200 bg-white/60 px-5 py-4 text-sm leading-6 text-stone-500">Investinfo는 정보 제공 및 교육 목적의 서비스이며 투자 자문이나 매수·매도 권유를 제공하지 않습니다. 13F는 분기 말 기준의 지연 공개 자료입니다.</aside>
    </Container>
  </>;
}
